import jsPDF from "jspdf";

interface BreakdownRow {
  semester: number;
  gpa: number;
  credits: number;
  weighted: number;
}

export function generateCgpaReport(cgpa: number, breakdown: BreakdownRow[]) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("CGPA Report", pageWidth / 2, y, { align: "center" });
  y += 12;

  // Subtitle
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated on ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, pageWidth / 2, y, { align: "center" });
  doc.setTextColor(0, 0, 0);
  y += 14;

  // CGPA result box
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(20, y, pageWidth - 40, 28, 4, 4, "F");
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("Your CGPA", pageWidth / 2, y + 10, { align: "center" });
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text(cgpa.toFixed(2), pageWidth / 2, y + 23, { align: "center" });
  y += 38;

  // Table header
  const colX = [25, 65, 105, 145];
  const colLabels = ["Semester", "GPA", "Credits", "Weighted"];

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setFillColor(230, 230, 230);
  doc.rect(20, y, pageWidth - 40, 10, "F");
  colLabels.forEach((label, i) => {
    doc.text(label, colX[i], y + 7);
  });
  y += 12;

  // Table rows
  doc.setFont("helvetica", "normal");
  breakdown.forEach((row, index) => {
    if (index % 2 === 0) {
      doc.setFillColor(250, 250, 250);
      doc.rect(20, y - 2, pageWidth - 40, 9, "F");
    }
    doc.text(`Sem ${row.semester}`, colX[0], y + 5);
    doc.text(row.gpa.toString(), colX[1], y + 5);
    doc.text(row.credits.toString(), colX[2], y + 5);
    doc.text(row.weighted.toString(), colX[3], y + 5);
    y += 9;
  });

  // Totals
  y += 4;
  const totalCredits = breakdown.reduce((s, r) => s + r.credits, 0);
  const totalWeighted = breakdown.reduce((s, r) => s + r.weighted, 0);
  doc.setFont("helvetica", "bold");
  doc.setFillColor(230, 230, 230);
  doc.rect(20, y, pageWidth - 40, 10, "F");
  doc.text("Total", colX[0], y + 7);
  doc.text("", colX[1], y + 7);
  doc.text(totalCredits.toString(), colX[2], y + 7);
  doc.text(totalWeighted.toFixed(2), colX[3], y + 7);
  y += 18;

  // Formula
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 100, 100);
  doc.text("Formula: CGPA = Sum(GPA × Credits) / Total Credits", pageWidth / 2, y, { align: "center" });
  y += 8;
  doc.text("Generated by yourlearningmentor.com", pageWidth / 2, y, { align: "center" });

  doc.save("CGPA-Report.pdf");
}
