import jsPDF from "jspdf";

interface TargetGpaReportData {
  currentCgpa: number;
  currentCredits: number;
  nextCredits: number;
  targetCgpa: number;
  requiredGpa: number;
  achievable: boolean;
  scale: number;
}

export function generateTargetGpaReport(data: TargetGpaReportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Target GPA Report", pageWidth / 2, y, { align: "center" });
  y += 12;

  // Subtitle
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated on ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`,
    pageWidth / 2,
    y,
    { align: "center" }
  );
  doc.setTextColor(0, 0, 0);
  y += 14;

  // Result box
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(20, y, pageWidth - 40, 28, 4, 4, "F");
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text(
    data.achievable ? "Required GPA Next Semester" : "Target Not Achievable",
    pageWidth / 2,
    y + 10,
    { align: "center" }
  );
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text(
    data.achievable ? data.requiredGpa.toFixed(2) : "—",
    pageWidth / 2,
    y + 23,
    { align: "center" }
  );
  y += 38;

  // Input summary table
  const labels = [
    ["Current CGPA", data.currentCgpa.toFixed(2)],
    ["Current Total Credits", data.currentCredits.toString()],
    ["Next Semester Credits", data.nextCredits.toString()],
    ["Target CGPA", data.targetCgpa.toFixed(2)],
    ["Scale", `${data.scale}.0`],
  ];

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setFillColor(230, 230, 230);
  doc.rect(20, y, pageWidth - 40, 10, "F");
  doc.text("Input", 25, y + 7);
  doc.text("Value", 120, y + 7);
  y += 12;

  doc.setFont("helvetica", "normal");
  labels.forEach(([label, value], index) => {
    if (index % 2 === 0) {
      doc.setFillColor(250, 250, 250);
      doc.rect(20, y - 2, pageWidth - 40, 9, "F");
    }
    doc.text(label, 25, y + 5);
    doc.text(value, 120, y + 5);
    y += 9;
  });

  // Breakdown
  y += 8;
  const currentPoints = data.currentCgpa * data.currentCredits;
  const totalCredits = data.currentCredits + data.nextCredits;
  const targetPoints = data.targetCgpa * totalCredits;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Calculation Breakdown", 25, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const breakdownLines = [
    `Current Weighted Points: ${data.currentCgpa} × ${data.currentCredits} = ${currentPoints.toFixed(2)}`,
    `Total Credits After Next Sem: ${data.currentCredits} + ${data.nextCredits} = ${totalCredits}`,
    `Target Total Points: ${data.targetCgpa} × ${totalCredits} = ${targetPoints.toFixed(2)}`,
    `Points Gap to Fill: ${targetPoints.toFixed(2)} - ${currentPoints.toFixed(2)} = ${(targetPoints - currentPoints).toFixed(2)}`,
    `Required GPA: ${(targetPoints - currentPoints).toFixed(2)} / ${data.nextCredits} = ${data.requiredGpa.toFixed(2)}`,
  ];

  breakdownLines.forEach((line) => {
    doc.text(line, 25, y);
    y += 7;
  });

  // Formula
  y += 8;
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 100, 100);
  doc.text(
    "Formula: Required GPA = (Target CGPA × Total Credits - Current CGPA × Current Credits) / Next Credits",
    pageWidth / 2,
    y,
    { align: "center" }
  );
  y += 8;
  doc.text("Generated by yourlearningmentor.com", pageWidth / 2, y, {
    align: "center",
  });

  doc.save("Target-GPA-Report.pdf");
}
